version: "3"

services:
  node:
    build:
      context: ./node
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./app:/usr/src/app
    command: sh -c "npm install && chmod -R 777 node_modules && npm run start"
    ports:
      - "3000:3000"